Neos:
  Flow:
    security:
      authentication:
        providers:
          JwtAuthenticationProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\JwtAuthenticationProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JwtToken'
          DefaultProvider:
            provider: 'RFY\JWT\Security\Authentication\Provider\JsonWebAuthenticationProvider'
            token: 'RFY\JWT\Security\Authentication\Token\JsonWebToken'
            entryPoint: 'HttpBasic'
    http:
      middlewares:
        'RFY.JWT:getJwtToken':
          middleware: 'RFY\JWT\Http\GetJwtTokenMiddleware'
        'RFY.JWT:setJwtToken':
          position: 'start'
          middleware: 'RFY\JWT\Http\SetJwtTokenMiddleware'

RFY:
  JWT:
    response:
      headers:
        'Access-Control-Allow-Origin': '*'
    key: ~ # pls set within your project configuration
    algorithms:
      - HS256
    tokenSources: # you can use 'cookie' or 'header' token sources
      - from: header
        name: Authorization
      #- from: cookie
      #  name: JWT
    tokenStrategy:
      'token': true
      'cookie': false
    inheritRolesFromOtherProviders: []
    claimMapping: []
